### PR TITLE
Revert PR #56.

### PR DESCRIPTION
**Pull request by sworisbreathing**
This should get #52 back to where it was before I messed things up. It reverts #56.

### CODE REVIEW

**Comment by craidler** [comment]
Makes #57 & #58 obsolete

**Comment by Ezriilc** [comment]
@sworisbreathing : I'm not sure that it was you that triggered this, as I was doing several things (merging another branch after your PR) that I don't properly know how to do, all at once.  I'm going to leave this here, until we see what I've done and how that may get fixed.

But, don't think I don't appreciate all you've done.  Once we get back to "normal", I do want to add your contributions to fix up on our Planet Editor bug(s).

Thanks again!

**Comment by sworisbreathing** [comment]
@Ezriilc well it doesn't build when they are floats, so I've definitely contributed to the problem.

Now that I'm able to build locally I'll make sure it's tested before I push up any more PRs :-)

**Comment by Ezriilc** [comment]
In my random, uninformed panic to fix the build, I seem to have already reverted this.

**Comment by Ezriilc** [comment]
I sure do appreciate everyone's help.  I simply could NOT do this without you.

**Pull request closed without merging**
